### ISSUE TITLE
Merge CS 241 and ECE 391?

### ISSUE THREAD

**Issue by ObviouslyGreen** [ieee-uiuc/technical-interview-review#1]
They are both related to computer systems. ECE 391 might be lower level, but there will be a lot of the same stuff between the two.

**Comment by anitgandhi** [comment]
I was considering merging them, but I wasn't sure how to. Should do we do the lowest common subset kind of thing (meaning CS 241)?

**Comment by ObviouslyGreen** [comment]
And maybe just add an extra section at the end for 391? Just thought they should be merged since they probably share more than topics than the differ.

**Comment by milanocookies93** [comment]
I would actually recommend keeping them separate. Other than synchronization, there's little content they have in common.

**Comment by anitgandhi** [comment]
I'm going to have to agree with @milanocookies93 , they're actually different levels of systems work and what you learn is different in each, barring synchronization at least. 

I'm sure copy/paste won't be a problem for any common items
